language: python
matrix:
	include:
		- python: 3.9
		  dist: xenial
		- python: 3.10
		  dist: xenial
stages:
	- lint
	- test

before_install:
	- pip install --upgrade pip
	- pip install poetry

install:
	- poetry install -v

jobs:
	include:
		- stage: lint
		  script: 
			  - poetry run flake8 basisopt tests
		- stage: test
		  script:
			  - poetry run pytest --cov

		
		
			  